---
apiVersion: v1
data:
  values: |
    global:
      connectivity:
        bastion:
          enabled: true
      controlPlane:
        replicas: 3
      metadata:
        name: nick2
        organization: giantswarm
      providerSpecific:
        location: westeurope
        subscriptionId: 6b1f6e4a-6d0e-4aa4-9a5a-fbaca65a23b3
      release:
        version: 33.0.1
kind: ConfigMap
metadata:
  creationTimestamp: null
  labels:
    giantswarm.io/cluster: nick2
  name: nick2-userconfig
  namespace: org-giantswarm
---
apiVersion: application.giantswarm.io/v1alpha1
kind: App
metadata:
  labels:
    app-operator.giantswarm.io/version: 0.0.0
  name: nick2
  namespace: org-giantswarm
spec:
  catalog: cluster
  config:
    configMap:
      name: ""
      namespace: ""
    secret:
      name: ""
      namespace: ""
  kubeConfig:
    context:
      name: ""
    inCluster: true
    secret:
      name: ""
      namespace: ""
  name: cluster-azure
  namespace: org-giantswarm
  userConfig:
    configMap:
      name: nick2-userconfig
      namespace: org-giantswarm
  version: ""
