{{- if .Values.verticalPodAutoscaler.enabled }}
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: {{ include "resource.default.name"  . }}
  namespace: {{ include "resource.default.namespace" . }}
  labels:
    {{- include "labels.common" . | nindent 4 }}
spec:
  resourcePolicy:
    containerPolicies:
    - containerName: {{ .Chart.Name }}
      controlledResources:
        - cpu
        - memory
      minAllowed:
        cpu: {{ .Values.verticalPodAutoscaler.minAllowed.cpu }}
        memory: {{ .Values.verticalPodAutoscaler.minAllowed.memory }}
      maxAllowed:
        cpu: {{ .Values.verticalPodAutoscaler.maxAllowed.cpu }}
        memory: {{ .Values.verticalPodAutoscaler.maxAllowed.memory }}
      mode: Auto
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "resource.default.name"  . }}
  updatePolicy:
    updateMode: {{ .Values.verticalPodAutoscaler.updateMode }}
{{- end }} 
